### ISSUE TITLE
PDM to PCM in STM32F4Discovery

### ISSUE THREAD

**Issue by j054n** [olegv142/pdm_fir#1]
Hi Mr. Oleg,
Trying to use your filter functions in this platform for sampling at 96KHz a modulated signal on a carrier of 16KHz, I can not obtain good results, I dont know if it's not posible or I'm using bad filter parameters.
Do you have any suggest or any example of using your code?
Thanks in advance.

**Comment by olegv142** [comment]
Hello,
The code repository contains python script for creating filter parameters.
I personally don't use this code currently but it should work.
Regards,
 Oleg.

2018-05-28 20:33 GMT+03:00 j054n <notifications@github.com>:
